# Base URL
BASE_URL=https://api-test.starlajewels.com/api

# Positive login
valid_email=test@test.com
valid_password=test1234

# Negative login
invalid_email=wrong@test.com
invalid_password=wrong123
sql_injection=' OR 1=1 --

# Inventory data
categoryId=2
vendorId=3
stockStatusId=12
organisationId=1

item_name=Gold Ring
item_description=22K Wedding Ring
vendor_design_code=VD-1001
gross_weight=10.5
cost=55000
stock_owner_type=VENDOR